name: Tests

on:
  push:
    branches: [ "main" , "add_cicd_pipeline"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -f docker/tests.dockerfile -t qa_bot_tests .

    - name: Run Tests
      run: docker run --rm qa_bot_tests